In [ ]:
!pip install torch

In [ ]:
import torch
import numpy as np

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [ ]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Linear Regression from Scratch


In [ ]:
#weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)


tensor([[-0.0299, -0.0126,  0.7424],
        [ 0.5652, -1.6147, -0.8500]], requires_grad=True)
tensor([-1.4262, -0.3169], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t()+b

In [ ]:
pred=model(inputs)
print(pred)

tensor([[  27.4647, -103.7920],
        [  42.2504, -145.3768],
        [  37.3357, -216.8132],
        [  22.4450,  -43.5494],
        [  47.2624, -175.8281]], grad_fn=<AddBackward0>)


In [ ]:
print(targets) #comparing with the inputs

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff * diff)/diff.numel() #mean square error

In [ ]:
loss=mse(pred,targets)
print(loss)

tensor(31877.7930, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()# partial differentiation / gradient

In [ ]:
print(w)
print(w.grad)

tensor([[-0.0299, -0.0126,  0.7424],
        [ 0.5652, -1.6147, -0.8500]], requires_grad=True)
tensor([[ -3302.9175,  -4319.3037,  -2465.7378],
        [-18820.0059, -22393.4609, -13429.7246]])


In [ ]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[ 0.0691,  0.1170,  0.8163],
        [ 1.1298, -0.9429, -0.4471]], requires_grad=True)
tensor([-1.4249, -0.3100], requires_grad=True)


In [ ]:
pred=model(inputs)
loss=mse(pred,targets)
print(loss)

tensor(8343.9287, grad_fn=<DivBackward0>)


In [ ]:
for i in range(100):
  pred=model(inputs)
  loss=mse(pred,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()#running 100 epochs


In [ ]:
pred=model(inputs)
loss=mse(pred,targets)
print(loss)

tensor(178.6309, grad_fn=<DivBackward0>)
